locale: en_GB.UTF-8
zone: Europe/Budapest
zoneinfo_path: /usr/share/zoneinfo/Europe/Budapest
supervisor: systemd
#supervisor: supervisord
offline_source: files/ready2use-2.0-3.2.war
download_war: false
install_ready2use: true
cmdbuild_url: https://sourceforge.net/projects/cmdbuild/files/3.2/cmdbuild-3.2.war
ready2use_url: https://sourceforge.net/projects/cmdbuild/files/ready2use-2.0/Core%20updates/ready2use-2.0-3.2/ready2use-2.0-3.2.war

# To use sourceforge slow download, set to true!

# Java
#JAVA_DL_URL: http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.rpm
#JAVA_DL_PATH: /usr/local/src/jdk-8u77-linux-x64.rpm

# Tomcat URL
#TOMCAT_DL_URL: https://www.apache.org/dist/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz
#TOMCAT_VER: 8.5.50
TOMCAT_DL_URL: https://downloads.apache.org/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
TOMCAT_VER: 9.0.31

# Postgres URL
#postgre_repo_v6: https://yum.postgresql.org/10/redhat/rhel-6-x86_64/pgdg-centos10-10-2.noarch.rpm
#postgre_repo_v7: https://yum.postgresql.org/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
JDBC_URL: https://jdbc.postgresql.org/download/postgresql-42.2.10.jar
jdbc_install: false

# CMDBuild
CMDBUILD_VER: 3.2
db_name: cmdbuild32
db_user: cmdbuser
db_password: cmdbuser
db_admin_user: postgres
db_admin_password: postgres
# db_type could be demo | empty
db_type: empty