---
all:
  children:
    cmdbuild:
      hosts:
        cmdbuild_host1:
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_host: 172.17.0.2
          ansible_port: 22
          ansible_user: ansible
          ansible_connection: ssh
          ansible_ssh_pass: ansible
